### ISSUE TITLE
Walk bug

### ISSUE THREAD

**Issue by Zoiter7** [AlonsoAliaga/BetterRevive#1]
**Bug**: You can walk when you are down (bleeding).

**Steps:**
1. Get to bleeding status
2. Press Shift and without release it you can walk free.
3. If you release it you come back to the original position.

Other bugs:
- If you die at the air the player sits in the air, it could be better to teleport it to the ground for better visualization.
- When you get killed and you are shifting the animation (sit position) is not applied. (related with the bug)
- When you shift when you are down the animation is not applied (related with the bug)

**Expected behavior**
When player is down, he shouldn't be able to walk.

**Important (please complete the following information):**
 - Java version: 8
 - Plugin version: 0.1-BETA
 - Server version: git-Paper-204 (MC: 1.16.3)

**Comment by Zoiter7** [comment]
**I don't know if this is a error or "none" for these command are not supported.**

When you set in the config for use permission for some command and you put "none" as is described in the config comments it gives an error.

`[21:48:44 INFO]: Zoiter7 issued server command: /giveup
[21:48:44 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'giveup' in plugin BetterRevive v0.1-BETA
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.3.jar:git-Paper-204]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.3.jar:git-Paper-204]
        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.dispatchCommand(CraftServer.java:802) ~[patched_1.16.3.jar:git-Paper-204]
        at net.minecraft.server.v1_16_R2.PlayerConnection.handleCommand(PlayerConnection.java:1908) ~[patched_1.16.3.jar:git-Paper-204]
        at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1719) ~[patched_1.16.3.jar:git-Paper-204]
        at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.3.jar:git-Paper-204]
        at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.3.jar:git-Paper-204]
        at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.3.jar:git-Paper-204]
        at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[patched_1.16.3.jar:git-Paper-204]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.3.jar:git-Paper-204]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.3.jar:git-Paper-204]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.3.jar:git-Paper-204]
        at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:1135) ~[patched_1.16.3.jar:git-Paper-204]
        at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:1128) ~[patched_1.16.3.jar:git-Paper-204]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.3.jar:git-Paper-204]
        at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:1089) ~[patched_1.16.3.jar:git-Paper-204]
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:1003) ~[patched_1.16.3.jar:git-Paper-204]
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-204]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
Caused by: java.lang.IllegalArgumentException: Permission name cannot be null
        at org.bukkit.permissions.PermissibleBase.hasPermission(PermissibleBase.java:73) ~[patched_1.16.3.jar:git-Paper-204]
        at org.bukkit.craftbukkit.v1_16_R2.entity.CraftHumanEntity.hasPermission(CraftHumanEntity.java:206) ~[patched_1.16.3.jar:git-Paper-204]
        at com.alonsoaliaga.betterrevive.commands.GiveUpCommand.onCommand(GiveUpCommand.java:26) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.3.jar:git-Paper-204]
        ... 18 more`

**config**:
Permissions:
  #Permission to use /giveup command
  Give-up: "none"

**Comment by AlonsoAliaga** [comment]
1.16.x has many visual bugs I cannot fix with plugins. However I'll look into this tomorrow

**Comment by AlonsoAliaga** [comment]
@Zoiter7 Can you join my discord so we can try a new build to see if it's fixed (at least movement part)?
This is the invite https://discord.gg/DEDaQhs

**Comment by AlonsoAliaga** [comment]
Issue partially solved in version 0.2-BETA.
Spigot visual glitch cannot be fixed due to plugins limitations
